import type { iChild } from "$lib/interface/index.js";

export enum UploadType {
  UPLOAD = "upload",
  URL = "url"
}


export const children: iChild[] = [
  {
    id: "child_001",
    name: "Jane Doe",
    image: {
      secure_url: "https://avatar.iran.liara.run/public/girl",
      public_id: "sample_image_001",
      type: "image",
      resource_type: "image",
    },
    codeName: "StarGazer",
    gallery: [
      "https://picsum.photos/200/300?image=2",
      "https://picsum.photos/200/300?image=3",
    ],
    email: "jane.doe@example.com",
    birthday: "2010-05-15",
    location: "island",
    gender: "female",
    mother: {
      id: "parent_001",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Alice Johnson",
      type: "mother",
      image: "https://avatar.iran.liara.run/public/74",
      email: "alice.johnson@example.com",
      children: ["child_001"],
      phone: "+1234567890",
      address: "123 Island Ave, Lagos",
    },
    father: {
      id: "parent_002",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Robert Johnson",
      type: "father",
      image: "https://avatar.iran.liara.run/public/15",
      email: "robert.johnson@example.com",
      children: ["child_001"],
      phone: "+0987654321",
      address: "123 Island Ave, Lagos",
    },
    xata: {
      createdAt: new Date(),
      updatedAt: new Date(),
      version: 1,
    },
  },
  {
    id: "child_002",
    name: "John Smith",
    image: {
      secure_url: "https://avatar.iran.liara.run/public/boy",
      public_id: "sample_image_002",
      type: "image",
      resource_type: "image",
    },
    codeName: "SkyWalker",
    gallery: [
      "https://picsum.photos/200/300?image=7",
      "https://picsum.photos/200/300?image=8",
    ],
    email: "john.smith@example.com",
    birthday: "2012-08-22",
    location: "mainland",
    gender: "male",
    mother: {
      id: "parent_003",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Mary Smith",
      type: "mother",
      image: "https://avatar.iran.liara.run/public/73",
      email: "mary.smith@example.com",
      children: ["child_002"],
      phone: "+2345678901",
      address: "456 Mainland Rd, Lagos",
    },
    father: {
      id: "parent_004",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "James Smith",
      type: "father",
      image: "https://avatar.iran.liara.run/public/37",
      email: "james.smith@example.com",
      children: ["child_002"],
      phone: "+1098765432",
      address: "456 Mainland Rd, Lagos",
    },
    xata: {
      createdAt: new Date(),
      updatedAt: new Date(),
      version: 1,
    },
  },
  {
    id: "child_003",
    name: "Emily Brown",
    image: {
      secure_url: "https://avatar.iran.liara.run/public/girl2",
      public_id: "sample_image_003",
      type: "image",
      resource_type: "image",
    },
    codeName: "MoonWalker",
    gallery: [
      "https://picsum.photos/200/300?image=9",
      "https://picsum.photos/200/300?image=10",
    ],
    email: "emily.brown@example.com",
    birthday: "2011-11-11",
    location: "abroad",
    gender: "female",
    mother: {
      id: "parent_005",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Patricia Brown",
      type: "mother",
      image: "https://avatar.iran.liara.run/public/75",
      email: "patricia.brown@example.com",
      children: ["child_003"],
      phone: "+3456789012",
      address: "789 Abroad St, New York",
    },
    father: {
      id: "parent_006",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Michael Brown",
      type: "father",
      image: "https://avatar.iran.liara.run/public/38",
      email: "michael.brown@example.com",
      children: ["child_003"],
      phone: "+2109876543",
      address: "789 Abroad St, New York",
    },
    xata: {
      createdAt: new Date(),
      updatedAt: new Date(),
      version: 1,
    },
  },
  {
    id: "child_004",
    name: "Sophia Green",
    image: {
      secure_url: "https://avatar.iran.liara.run/public/girl3",
      public_id: "sample_image_004",
      type: "image",
      resource_type: "image",
    },
    codeName: "EarthProtector",
    gallery: [
      "https://picsum.photos/200/300?image=11",
      "https://picsum.photos/200/300?image=12",
    ],
    email: "sophia.green@example.com",
    birthday: "2013-04-10",
    location: "island",
    gender: "female",
    mother: {
      id: "parent_007",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Hannah Green",
      type: "mother",
      image: "https://avatar.iran.liara.run/public/77",
      email: "hannah.green@example.com",
      children: ["child_004"],
      phone: "+5678901234",
      address: "123 Green Ave, Lagos",
    },
    father: {
      id: "parent_008",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Jacob Green",
      type: "father",
      image: "https://avatar.iran.liara.run/public/40",
      email: "jacob.green@example.com",
      children: ["child_004"],
      phone: "+8765432109",
      address: "123 Green Ave, Lagos",
    },
    xata: {
      createdAt: new Date(),
      updatedAt: new Date(),
      version: 1,
    },
  },
  {
    id: "child_005",
    name: "Oliver White",
    image: {
      secure_url: "https://avatar.iran.liara.run/public/boy2",
      public_id: "sample_image_005",
      type: "image",
      resource_type: "image",
    },
    codeName: "SunChaser",
    gallery: [
      "https://picsum.photos/200/300?image=13",
      "https://picsum.photos/200/300?image=14",
    ],
    email: "oliver.white@example.com",
    birthday: "2015-09-18",
    location: "mainland",
    gender: "male",
    mother: {
      id: "parent_009",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "Linda White",
      type: "mother",
      image: "https://avatar.iran.liara.run/public/78",
      email: "linda.white@example.com",
      children: ["child_005"],
      phone: "+6789012345",
      address: "345 Mainland Rd, Lagos",
    },
    father: {
      id: "parent_010",
      xata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        version: 1,
      },
      name: "David White",
      type: "father",
      image: "https://avatar.iran.liara.run/public/41",
      email: "david.white@example.com",
      children: ["child_005"],
      phone: "+9876543210",
      address: "345 Mainland Rd, Lagos",
    },
    xata: {
      createdAt: new Date(),
      updatedAt: new Date(),
      version: 1,
    },
  },
  // Objects for child_006 to child_011 follow a similar structure
];